# Build stage
FROM golang:1.25 AS backend-builder
WORKDIR /app
COPY backend/go.mod backend/go.sum ./
RUN go mod download
COPY backend ./
RUN go build -o server ./cmd/webserver

# Runtime stage
FROM gcr.io/distroless/base-debian12 AS runtime
WORKDIR /app
COPY --from=backend-builder /app/server .
USER nonroot:nonroot
EXPOSE 8080
CMD ["./server"]
