openapi: 3.0.3
info:
  title: Wo-App API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /login:
    post:
      summary: Order to login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginOrder'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUser'
  /managePlant:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
  /groups/{groupUuid}/manageFarms:
    get:
      summary: Get Farms by GroupUUID
      parameters:
        - name: groupUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FarmInfo'
    post:
      summary: Register New Farm
      parameters:
        - name: groupUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FarmInfoDetail'
      responses:
        '200':
          description: OK
    put:
      summary: Update Farm FarmInfo
      parameters:
        - name: groupUuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FarmInfoDetail'
      responses:
        '200':
          description: OK
components:
  schemas:
    LoginOrder:
      type: object
      properties:
        userId:
          type: string
        groupId:
          type: string
        password:
          type: string
          format: password
    LoginUser:
      type: object
      properties:
        userUuid:
          type: string
          format: uuid
        groupUuid:
          type: string
          format: uuid
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
    FarmInfo:
      type: object
      required:
        - farmName
        - farmUuid
      properties:
        farmName:
          type: string
        farmUuid:
          type: string
          format: uuid
    FarmInfoDetail:
      type: object
      required:
        - farmName
        - farmYear
        - farmSeasons
        - farmLength
        - farmWidth
      properties:
        farmName:
          type: string
        farmYear:
          type: integer
        farmSeasons:
          type: array
          items:
            type: integer
        farmLength:
          type: string
        farmWidth:
          type: string
        furrowNumber:
          type: integer
        furrowWidth:
          type: string
