openapi: 3.0.3
info:
  title: Wo-App API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /login:
    post:
      summary: Order to login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginOrder'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUser'
  /managePlant:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    LoginOrder:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
          format: password
    LoginUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
