openapi: 3.1.0
info:
  title: Wo-App API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /plant:
    get:
      summary: Get all users
      responses:
        '200':
          description: OK
          content:
            applicattion/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: init64
        title:
          type: string
