openapi: 3.1.0
info:
  title: Wo-App API
  version: 1.0.0
servers:
- url: http://localhost:8080/api
paths:
  /plant:
    get:
      responses:
        "200":
          content:
            applicattion/json:
              schema:
                items:
                  $ref: "#/components/schemas/Item"
                type: array
          description: OK
      summary: Get all users
components:
  schemas:
    Item:
      properties:
        id:
          format: init64
          type: integer
        title:
          type: string
