name: backend-CI

on:
  push:
    branches:
      - main 

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build ./...
        working-directory: ./backend
      
      - name: test
        run: go test -race ./...
        working-directory: ./backend
      
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend