name: CD  to Render

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["backend-CI"]
    types:
      - completed

jobs:
  backend-deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & Push Docker image
        run: |
          IMAGE = ghcr.io/${{ github.repository }}/app:latest
          docker build -t $IMAGE .
          docker push $IMAGE
        
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"clearCache":false}' \
            https://api.render.com/v1/services/${{secrets.RENDER_SERVICE_ID }}/deploys